apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: TestApp
spec:
  destination:
    name: my-demo-app
    namespace: demo-app
    server: https://kubernetes.default.svc
  source:
    path: demo
    repoURL: https://github.com/asakuraa/test-app.git
    targetRevision: HEAD
  project: demo-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
